name: sfi

on:
  pull_request:
    branches:
    # I think this is necessary to trigger it in PR
    - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/status') || (github.event_name != 'schedule')

    name: Testing single file installer on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.6, 3.7]

    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: constructor
        environment-file: devtools/conda-envs/sfi.yaml
        auto-activate-base: false

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Run the installer
      shell: bash -l {0}
      run: |
        git clone https://github.com/openforcefield/toolkit-installer-constructor
        cd toolkit-installer-constructor
        python run.py
